package com.google.sps.utilities;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public final class PrefilledInformationConstants {
  // Constants in this class are influenced by https://cloud.google.com/natural-language/docs/categories
  public static final List<String> INTERESTS =
      new ArrayList<>(
          Arrays.asList(
              "Arts & Entertainment",
              "Autos & Vehicles",
              "Beauty",
              "Books & Literature",
              "Business & Industrial",
              "Computers & Electronics",
              "Finance",
              "Educational",
              "Food & Drink",
              "Games",
              "Hobbies & Leisure",
              "Home & Garden",
              "Internet & Telecom",
              "Jobs & Education",
              "Law & Government",
              "Professional",
              "News",
              "Online Communities",
              "Social Issues & Advocacy",
              "Religion & Belief",
              "Pets & Animals",
              "Real Estate",
              "Science",
              "Shopping",
              "Sports",
              "Travel"));
  public static final List<String> SKILLS =
      new ArrayList<>(
          Arrays.asList(
              "american football",
              "archery",
              "badminton",
              "baseball",
              "baking",
              "basketball",
              "beach volleyball",
              "bicycling",
              "billiards",
              "bodybuilding",
              "bowling",
              "boxing",
              "cheerleading",
              "chess",
              "competitions",
              "cooking",
              "cricket",
              "curling",
              "dancing",
              "darts",
              "debate",
              "disc golf",
              "dodgeball",
              "fantasy sports",
              "flag football",
              "golfing",
              "handball",
              "horseback riding",
              "ice hockey",
              "lacrosse",
              "paintball",
              "roller skating",
              "rugby",
              "sailing",
              "skateboarding",
              "skiing",
              "snowboarding",
              "soccer",
              "surfing",
              "swimming",
              "table tennis",
              "tennis",
              "ultimate frisbee",
              "volleyball",
              "wrestling",
              "calligraphy",
              "cartooning",
              "cards",
              "ceramics",
              "coloring",
              "crocheting",
              "cross-stitch",
              "drawing",
              "embroidery",
              "fashion",
              "knitting",
              "origami",
              "painting",
              "photography",
              "pottery",
              "sewing",
              "singing",
              "sketching",
              "taxidermy",
              "textiles",
              "crosswords",
              "dolls",
              "electronics",
              "history",
              "jigsaw puzzles",
              "laser tag",
              "magic",
              "mahjong",
              "meditation",
              "gymnastics",
              "robotics",
              "sudoku",
              "tetris",
              "TV",
              "writing",
              "grilling",
              "bbq",
              "brewing",
              "cake decorating",
              "kombucha",
              "winemaking",
              "canning"));
}
